#include "board_pins.h"

void board_gpio_init(void)
{
  GPIO_InitTypeDef GPIO_InitStruct = {0};

  __HAL_RCC_GPIOA_CLK_ENABLE();
  __HAL_RCC_GPIOB_CLK_ENABLE();
  __HAL_RCC_GPIOC_CLK_ENABLE();

  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;

  GPIO_InitStruct.Pin = LED_RED_PIN | LED_BLUE_PIN;
  HAL_GPIO_Init(LED_RED_PORT, &GPIO_InitStruct);

  GPIO_InitStruct.Pin = LED_STATUS_RED_PIN | LED_STATUS_BLUE_PIN;
  HAL_GPIO_Init(LED_STATUS_RED_PORT, &GPIO_InitStruct);

  GPIO_InitStruct.Pin = LED_SCL_PIN | LED_SCP_PIN;
  HAL_GPIO_Init(LED_SCL_PORT, &GPIO_InitStruct);

  GPIO_InitStruct.Pin = LEG_POWER_PIN;
  HAL_GPIO_Init(LEG_POWER_PORT, &GPIO_InitStruct);

  GPIO_InitStruct.Mode = GPIO_MODE_INPUT;
  GPIO_InitStruct.Pull = GPIO_PULLUP;
  GPIO_InitStruct.Pin = BTN_DOG_PIN;
  HAL_GPIO_Init(BTN_DOG_PORT, &GPIO_InitStruct);

  HAL_GPIO_WritePin(LED_RED_PORT, LED_RED_PIN, GPIO_PIN_RESET);
  HAL_GPIO_WritePin(LED_BLUE_PORT, LED_BLUE_PIN, GPIO_PIN_RESET);
  HAL_GPIO_WritePin(LED_STATUS_RED_PORT, LED_STATUS_RED_PIN, GPIO_PIN_RESET);
  HAL_GPIO_WritePin(LED_STATUS_BLUE_PORT, LED_STATUS_BLUE_PIN, GPIO_PIN_RESET);
  HAL_GPIO_WritePin(LED_SCL_PORT, LED_SCL_PIN, GPIO_PIN_RESET);
  HAL_GPIO_WritePin(LED_SCP_PORT, LED_SCP_PIN, GPIO_PIN_RESET);
  HAL_GPIO_WritePin(LEG_POWER_PORT, LEG_POWER_PIN, GPIO_PIN_SET);
}
